const mongoose = require('mongoose');

const P2P_transaction = mongoose.Schema(
    {
        user_id: { type: String, required: false },
        postAd_user: { type: String, required: true },
        post_name: { type: String, required: false },
        order_id : { type: String, required: false },
        trader_id : { type: String, required: false },
        add_id : { type: String, required: false },
        side: { type: String, required: false },
        base_currency: { type: String, required: true },
        quote_currency: { type: String, required: true },
        base_currency_id: { type: String, required: true },
        receiving_amount : { type : Number, required: false },
        quote_currency_id: { type: String, required: true },
        base_short_name: { type: String, required: true },
        quote_short_name: { type: String, required: true },
        deposit_slip: {type: String, required: false},
        transaction_number: { type: String, required: false },
        price_type: { type: String, required: false },
        description : { type: String, default: '', required: false },
        checkAvailability : { type: String, required: false },
        fixed_price: { type: Number, required: false , default: 0 },
        floating_price: { type: Number, required: false , default: 0 },
        amount: { type: Number, required: false , default: 0 },
        volume: { type: Number, required: false , default: 0 },
        payment_method: { type: Array, required: false },
        payment_timestamp: { type: String, required: false },
        payment_time: { type: String, required: true }, 
        kyc: { type: Boolean, required: false, default: false },
        kycStatus: { type: String, required: false, default: '' },
        registered_days: { type: Number, required: false, default: 0 },
        dayStatus: { type: String, required: false, default: ''},
        ratings: { type: Number, required: false, default: 0},
        totalTransactions: { type: Number, required: false, default: 0 },
        successfullOrders: { type: Number, required: false, default: 0 },
        refundedToSeller: { type: Boolean, required: false, default: false },
        trades: { type: String, required: false, default: ''},
        counterCurrency: { type: String, required: false, default: '' },
        counterCurrencyStatus: { type: String, required: false, default: ''},
        currencyAmount: { type: Number, required: false, default: 0 },
        status: { type: String, required: false, default: ''},
        trader_status: { type: String, required: false, default: 'PENDING'},
        merchant_status: { type: String, required: false, default: 'PENDING'},
    }, { timestamps: true }
)

module.exports = mongoose.model('P2P_transaction', P2P_transaction);